/**
 * Frontend Permissions Constants
 * 
 * Mirror of server/constants/permissions.js for frontend use.
 * Keep in sync with the backend definitions.
 */

export const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  VIEWER: 'VIEWER',
};

export const ROLE_HIERARCHY = {
  [ROLES.VIEWER]: 0,
  [ROLES.MEMBER]: 1,
  [ROLES.ADMIN]: 2,
  [ROLES.OWNER]: 3,
};

export const PERMISSIONS = {
  WORKSPACE_VIEW: 'workspace:view',
  WORKSPACE_EDIT: 'workspace:edit',
  WORKSPACE_DELETE: 'workspace:delete',
  MEMBERS_VIEW: 'members:view',
  MEMBERS_MANAGE: 'members:manage',
  ACCOUNTS_VIEW: 'accounts:view',
  ACCOUNTS_MANAGE: 'accounts:manage',
  CONTACTS_VIEW: 'contacts:view',
  CONTACTS_MANAGE: 'contacts:manage',
  CONTACTS_DELETE: 'contacts:delete',
  BROADCASTS_VIEW: 'broadcasts:view',
  BROADCASTS_MANAGE: 'broadcasts:manage',
  TEMPLATES_VIEW: 'templates:view',
  TEMPLATES_MANAGE: 'templates:manage',
  MEDIA_VIEW: 'media:view',
  MEDIA_MANAGE: 'media:manage',
  WEBHOOKS_VIEW: 'webhooks:view',
  WEBHOOKS_MANAGE: 'webhooks:manage',
  INBOX_VIEW: 'inbox:view',
  INBOX_SEND: 'inbox:send',
  SYSTEM_MANAGE: 'system:manage',
  AUDIT_VIEW: 'audit:view',
};

export const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.WORKSPACE_EDIT,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.ACCOUNTS_VIEW,
    PERMISSIONS.ACCOUNTS_MANAGE,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.CONTACTS_DELETE,
    PERMISSIONS.BROADCASTS_VIEW,
    PERMISSIONS.BROADCASTS_MANAGE,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.TEMPLATES_MANAGE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_MANAGE,
    PERMISSIONS.WEBHOOKS_VIEW,
    PERMISSIONS.WEBHOOKS_MANAGE,
    PERMISSIONS.INBOX_VIEW,
    PERMISSIONS.INBOX_SEND,
    PERMISSIONS.AUDIT_VIEW,
  ],
  [ROLES.MEMBER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.ACCOUNTS_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.BROADCASTS_VIEW,
    PERMISSIONS.BROADCASTS_MANAGE,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.TEMPLATES_MANAGE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_MANAGE,
    PERMISSIONS.INBOX_VIEW,
    PERMISSIONS.INBOX_SEND,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.ACCOUNTS_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.BROADCASTS_VIEW,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.INBOX_VIEW,
  ],
};

export const hasPermission = (role, permission) => {
  return ROLE_PERMISSIONS[role]?.includes(permission) || false;
};

export const isRoleAtLeast = (roleA, roleB) => {
  return (ROLE_HIERARCHY[roleA] ?? -1) >= (ROLE_HIERARCHY[roleB] ?? -1);
};
