export const ROLES = {
  OWNER: 'OWNER',
  ADMIN: 'ADMIN',
  MEMBER: 'MEMBER',
  VIEWER: 'VIEWER',
};

export const PERMISSIONS = {
  // Workspace management
  WORKSPACE_VIEW: 'workspace:view',
  WORKSPACE_EDIT: 'workspace:edit',
  WORKSPACE_DELETE: 'workspace:delete',
  
  // Member management
  MEMBERS_VIEW: 'members:view',
  MEMBERS_MANAGE: 'members:manage',
  
  // WhatsApp Accounts (WABA)
  ACCOUNTS_VIEW: 'accounts:view',
  ACCOUNTS_MANAGE: 'accounts:manage',
  
  // Contacts
  CONTACTS_VIEW: 'contacts:view',
  CONTACTS_MANAGE: 'contacts:manage',
  CONTACTS_DELETE: 'contacts:delete',
  
  // Broadcasts
  BROADCASTS_VIEW: 'broadcasts:view',
  BROADCASTS_MANAGE: 'broadcasts:manage',
  
  // Templates
  TEMPLATES_VIEW: 'templates:view',
  TEMPLATES_MANAGE: 'templates:manage',
  
  // Media
  MEDIA_VIEW: 'media:view',
  MEDIA_MANAGE: 'media:manage',
  
  // Webhooks
  WEBHOOKS_VIEW: 'webhooks:view',
  WEBHOOKS_MANAGE: 'webhooks:manage',
};

export const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: Object.values(PERMISSIONS),
  [ROLES.ADMIN]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.WORKSPACE_EDIT,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.MEMBERS_MANAGE,
    PERMISSIONS.ACCOUNTS_VIEW,
    PERMISSIONS.ACCOUNTS_MANAGE,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.CONTACTS_DELETE,
    PERMISSIONS.BROADCASTS_VIEW,
    PERMISSIONS.BROADCASTS_MANAGE,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.TEMPLATES_MANAGE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_MANAGE,
    PERMISSIONS.WEBHOOKS_VIEW,
    PERMISSIONS.WEBHOOKS_MANAGE,
  ],
  [ROLES.MEMBER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.ACCOUNTS_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.CONTACTS_MANAGE,
    PERMISSIONS.BROADCASTS_VIEW,
    PERMISSIONS.BROADCASTS_MANAGE,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.TEMPLATES_MANAGE,
    PERMISSIONS.MEDIA_VIEW,
    PERMISSIONS.MEDIA_MANAGE,
  ],
  [ROLES.VIEWER]: [
    PERMISSIONS.WORKSPACE_VIEW,
    PERMISSIONS.MEMBERS_VIEW,
    PERMISSIONS.ACCOUNTS_VIEW,
    PERMISSIONS.CONTACTS_VIEW,
    PERMISSIONS.BROADCASTS_VIEW,
    PERMISSIONS.TEMPLATES_VIEW,
    PERMISSIONS.MEDIA_VIEW,
  ],
};

export const hasPermission = (role, permission) => {
  return ROLE_PERMISSIONS[role]?.includes(permission) || false;
};
